// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using VoyadoEngage.Http;
using VoyadoEngage.Http.Exceptions;
using VoyadoEngage.Http.Extensions;
using VoyadoEngage.Http.Serialization;
using VoyadoEngage.Models;

namespace VoyadoEngage.Services;

public class MemberstatusService : BaseService
{
    internal MemberstatusService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>
    /// Gets the first found member that matches the query.
    ///
    /// Operation to get member overview. Is usually called from
    /// POS after a member gives some identification information
    /// this method returns the status together with contactId (GUID)
    /// and memberNumber (if available). The contactId may be used
    /// to get detailed contact information.
    ///
    /// Common identification fields that may be used in the query:
    /// socialSecurityNumber, email, mobilePhone, memberNumber and externalId
    ///
    /// The language of the returned answer is controlled by the language setting of the user connected to the API-key.
    /// </summary>
    /// <param name="query">```{fieldId}:{value}```, e.g. email:test@test.com</param>
    public async Task<MemberStatusModel> MemberStatusVGetAsync(
        string query,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(query, nameof(query));

        var request = new RequestBuilder(HttpMethod.Get, "api/v2/memberstatus")
            .SetQueryParameter("query", query)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);

        return await response
                .EnsureSuccessfulResponse()
                .Content.ReadFromJsonAsync<MemberStatusModel>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
