// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using VoyadoEngage.Http;
using VoyadoEngage.Http.Serialization;
using VoyadoEngage.Models;

namespace VoyadoEngage.Services;

public class SmsService : BaseService
{
    internal SmsService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>
    /// Send an SMS to one or multiple phone numbers.
    ///
    /// Phone numbers must be prefixed with a + and country code
    /// (e.g. +4670xxxxxxx for a Swedish mobile phone number).
    /// </summary>
    /// <param name="input">Message data.</param>
    public async Task<SendSmsResponse> SmsMessagesSendSmsToPhoneNumbersAsync(
        SendSmsRequest input,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "api/v2/sms/sendToPhoneNumbers")
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<SendSmsResponse>(
                    _jsonSerializerOptions,
                    cancellationToken
                )
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
