// This file was generated by liblab | https://liblab.com/

using System.Net.Http.Json;
using VoyadoEngage.Http;
using VoyadoEngage.Http.Serialization;
using VoyadoEngage.Models;

namespace VoyadoEngage.Services;

public class TrackingService : BaseService
{
    internal TrackingService(HttpClient httpClient)
        : base(httpClient) { }

    /// <summary>
    /// Register an update to a specific cart for a given contact. Should be the latest update of the cart.
    ///
    /// Request model:
    /// - CartReference: Unique identifier of the cart. Links the update to a specific cart. Ex: "006788ba-9f65-49c6-b3a0-2315d1854728"
    /// - Time: Time of the cart update. ISO8601 with Time Zone Designators. Ex: "2021-09-22T11:00:00+02:00"
    /// - ContactId: Contact id of the cart owner. GUID or short GUID. Ex: "ae16a9b4-f581-4568-8948-a96100b2afd4"
    /// - Language: Culture code of the cart. A corresponding product feed should be configured. Ex: "sv-SE"
    /// - Url: Url to the cart. Ex: "https://www.store.se/cart?id=006788ba-9f65-49c6-b3a0-2315d1854728"
    /// - Items: Collection of cart items. Ex: ```[{"Sku":"90183744","Quantity":1},{"Sku":"90156607","Quantity":1}]```
    /// </summary>
    public async Task<OkResult> CartRegisterCartAsync(
        CartApiModel input,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "api/v2/tracking/carts")
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<OkResult>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>
    /// Register a batch of cart updates. Cart updates are processed according to update time. If multiple cart updates are registered with the same identifier only the latest update (according to update time) is considered.
    ///
    /// Request model:
    /// - CartReference: Unique identifier of the cart. Links the update to a specific cart. Ex: "006788ba-9f65-49c6-b3a0-2315d1854728"
    /// - Time: Time of the cart update. ISO8601 with Time Zone Designators. Ex: "2021-09-22T11:00:00+02:00"
    /// - ContactId: Contact id of the cart owner. GUID or short GUID. Ex: "ae16a9b4-f581-4568-8948-a96100b2afd4"
    /// - Language: Culture code of the cart. A corresponding product feed should be configured. Ex: "sv-SE"
    /// - Url: Url to the cart. Ex: "https://www.store.se/cart?id=006788ba-9f65-49c6-b3a0-2315d1854728"
    /// - Items: Collection of cart items. Ex: ```[{"Sku":"90183744","Quantity":1},{"Sku":"90156607","Quantity":1}]```
    /// </summary>
    public async Task<OkResult> CartRegisterCartsAsync(
        List<CartApiModel> input,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "api/v2/tracking/carts/batch")
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<OkResult>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>
    /// Register a view of a specific product for a given contact.
    ///
    /// Request model:
    /// - ItemId: Unique SKU/Article Id/Item Id of the viewed product. Will be matched against SKU on the imported articles in Voyado. Ex: "123XYZ"
    /// - Category: Category of the product on the website. Will be used for filtering. Ex: "novels &gt; cormac mccarthy &gt; the road"
    /// - Time: Time of the product view. ISO8601 with Time Zone Designators. Ex: "2021-09-22T11:00:00+02:00".
    /// - ContactId: Contact id of the viewer. GUID or short GUID. Ex: "FF9FD9AF-6778-4714-B0FE-F6E6612840C8"
    /// - SessionId: Unique identifier of the session. Ex: "3b7e493b-5dfe-4b98-b6cf-049f2ea4309d"
    /// - NewSession: Boolean value that indicates that new session.
    /// - Language: Culture code of the cart. A corresponding product feed should be configured. Ex: "sv-SE"
    /// - Url: Url of the productview. Ex: "https://www.voyado.com?sku=eu901-011-v10"
    /// - ExternalReferrer: The external site that the user came from (clicked a link) Ex: "https://www.google.com"
    /// </summary>
    public async Task<object> ProductViewVRegisterProductViewAsync(
        ProductViewApiModel input,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "api/v2/tracking/productview")
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }

    /// <summary>
    /// Register a collection of views to specific products for given contacts.
    ///
    /// Request model:
    /// - ItemId: Unique SKU/Article Id/Item Id of the viewed product. Will be matched against SKU on the imported articles in Voyado. Ex: "123XYZ"
    /// - Category: Category of the product on the website. Will be used for filtering. Ex: "novels &gt; cormac mccarthy &gt; the road"
    /// - Time: Time of the product view. ISO8601 with Time Zone Designators. Ex: "2021-09-22T11:00:00+02:00"
    /// - ContactId: Contact id of the viewer. GUID or short GUID. Ex: "FF9FD9AF-6778-4714-B0FE-F6E6612840C8"
    /// - SessionId: Unique identifier of the session. Ex: "3b7e493b-5dfe-4b98-b6cf-049f2ea4309d"
    /// - NewSession: Boolean value that indicates that new session.
    /// - Language: Culture code of the cart. A corresponding product feed should be configured. Ex: "sv-SE"
    /// - Url: Url of the productview. Ex: "https://www.voyado.com?sku=eu901-011-v10"
    /// - ExternalReferrer: The external site that the user came from (clicked a link) Ex: "https://www.google.com"
    /// </summary>
    /// <param name="input">An array of JSON objects representing the Product View events</param>
    public async Task<object> ProductViewVRegisterProductViewsAsync(
        List<ProductViewApiModel> input,
        CancellationToken cancellationToken = default
    )
    {
        ArgumentNullException.ThrowIfNull(input, nameof(input));

        var request = new RequestBuilder(HttpMethod.Post, "api/v2/tracking/productviews")
            .SetContentAsJson(input, _jsonSerializerOptions)
            .Build();

        var response = await _httpClient
            .SendAsync(request, cancellationToken)
            .ConfigureAwait(false);
        response.EnsureSuccessStatusCode();

        return await response
                .Content.ReadFromJsonAsync<object>(_jsonSerializerOptions, cancellationToken)
                .ConfigureAwait(false) ?? throw new Exception("Failed to deserialize response.");
    }
}
