// This file was generated by liblab | https://liblab.com/

using VoyadoEngage;
using VoyadoEngage.Config;
using Environment = VoyadoEngage.Http.Environment;

var config = new VoyadoEngageConfig
{
    Environment = Environment.Default,
    AccessToken = "YOUR_ACCESS_TOKEN"
};

var client = new VoyadoEngageClient(config);

var response = await client.Achievements.AchievementsGetAllAchievementsAsync(8, 2);

Console.WriteLine(response);
