// This file was generated by liblab | https://liblab.com/

using Environment = VoyadoEngage.Http.Environment;

namespace VoyadoEngage.Config;

/// <summary>
/// Configuration options for the VoyadoEngageClient.
/// </summary>
public record VoyadoEngageConfig(
    /// <value>The environment to use for the SDK.</value>
    Environment? Environment = null,
    /// <value>The access token.</value>
    string? AccessToken = null
);
