// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record AddCheckpointToChallengeAssignmentResult(
    [property:
        JsonPropertyName("missingContactIds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? MissingContactIds = null,
    [property:
        JsonPropertyName("missingDefinitionIds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? MissingDefinitionIds = null,
    [property:
        JsonPropertyName("notAccepted"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ChallengeCheckPointDto>? NotAccepted = null
);
