// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record ApiAdjustRewardPointsResponse(
    [property: JsonPropertyName("contactId")] string ContactId,
    [property: JsonPropertyName("totalRewardPoints")] double TotalRewardPoints
);
