// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record ApiPromotionRedemptionChannelModel(
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ApiPromotionRedemptionChannelModel.ApiPromotionRedemptionChannelModelType? Type_ = null,
    [property:
        JsonPropertyName("valueType"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        ApiPromotionRedemptionChannelModel.ApiPromotionRedemptionChannelModelValueType? ValueType =
        null,
    /// <value>
    /// The type of "Value" depends on "ValueType".
    /// "MONEY" returns a Money object (Amount+Currency), "EXTERNALOFFER" and "MANUAL" returns a string ("Promotion"). "PERCENT" returns an integer.
    /// </value>
    [property:
        JsonPropertyName("value"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        object? Value = null,
    [property:
        JsonPropertyName("localValues"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<object>? LocalValues = null,
    [property:
        JsonPropertyName("instruction"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Instruction = null
)
{
    public record ApiPromotionRedemptionChannelModelType : ValueEnum<string>
    {
        internal ApiPromotionRedemptionChannelModelType(string value)
            : base(value) { }

        public ApiPromotionRedemptionChannelModelType()
            : base("POS") { }

        public static ApiPromotionRedemptionChannelModelType Pos = new("POS");
        public static ApiPromotionRedemptionChannelModelType Ecom = new("ECOM");
        public static ApiPromotionRedemptionChannelModelType Other = new("OTHER");
    }

    public record ApiPromotionRedemptionChannelModelValueType : ValueEnum<string>
    {
        internal ApiPromotionRedemptionChannelModelValueType(string value)
            : base(value) { }

        public ApiPromotionRedemptionChannelModelValueType()
            : base("PERCENT") { }

        public static ApiPromotionRedemptionChannelModelValueType Percent = new("PERCENT");
        public static ApiPromotionRedemptionChannelModelValueType Money = new("MONEY");
        public static ApiPromotionRedemptionChannelModelValueType Externaloffer =
            new("EXTERNALOFFER");
        public static ApiPromotionRedemptionChannelModelValueType Manual = new("MANUAL");
        public static ApiPromotionRedemptionChannelModelValueType Swipe = new("SWIPE");
    }
}
