// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

/// <summary>Cart model</summary>
public record CartApiModel(
    /// <value>Unique cart reference</value>
    [property:
        JsonPropertyName("cartReference"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? CartReference = null,
    /// <value>Last change date</value>
    [property:
        JsonPropertyName("time"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Time = null,
    /// <value>Contact identifier</value>
    [property:
        JsonPropertyName("contactId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ContactId = null,
    /// <value>Language</value>
    [property:
        JsonPropertyName("language"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Language = null,
    /// <value>Url to cart</value>
    [property:
        JsonPropertyName("url"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Url = null,
    /// <value>Cart items</value>
    [property:
        JsonPropertyName("items"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<CartItemApiModel>? Items = null
);
