// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record ChallengeGetChallengesFilter : ValueEnum<string>
{
    internal ChallengeGetChallengesFilter(string value)
        : base(value) { }

    public ChallengeGetChallengesFilter()
        : base("All") { }

    public static ChallengeGetChallengesFilter All = new("All");
    public static ChallengeGetChallengesFilter Active = new("Active");
    public static ChallengeGetChallengesFilter Completed = new("Completed");
    public static ChallengeGetChallengesFilter NotCompleted = new("NotCompleted");
}
