// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record ChallengeCheckPointDto(
    [property:
        JsonPropertyName("definitionId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? DefinitionId = null,
    [property:
        JsonPropertyName("contactId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ContactId = null,
    [property:
        JsonPropertyName("checkpointAmount"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        long? CheckpointAmount = null
);
