// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record ChallengeGetChallengeDefinitionsStatus : ValueEnum<string>
{
    internal ChallengeGetChallengeDefinitionsStatus(string value)
        : base(value) { }

    public ChallengeGetChallengeDefinitionsStatus()
        : base("All") { }

    public static ChallengeGetChallengeDefinitionsStatus All = new("All");
    public static ChallengeGetChallengeDefinitionsStatus Active = new("Active");
    public static ChallengeGetChallengeDefinitionsStatus Draft = new("Draft");
    public static ChallengeGetChallengeDefinitionsStatus Scheduled = new("Scheduled");
    public static ChallengeGetChallengeDefinitionsStatus Ended = new("Ended");
}
