// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record ChangeType : ValueEnum<string>
{
    internal ChangeType(string value)
        : base(value) { }

    public ChangeType()
        : base("Created") { }

    public static ChangeType Created = new("Created");
    public static ChangeType Updated = new("Updated");
    public static ChangeType Deleted = new("Deleted");
}
