// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

/// <summary>An enrichment value for a certain BCI variable</summary>
public record EnrichmentVariable(
    /// <value>BCI variable identifier</value>
    [property:
        JsonPropertyName("bciVariableId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? BciVariableId = null,
    /// <value>BCI Value</value>
    [property:
        JsonPropertyName("bciValue"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? BciValue = null,
    /// <value>Variable name in Voyado</value>
    [property:
        JsonPropertyName("variableName"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? VariableName = null,
    /// <value>Mapped value in Voyado</value>
    [property:
        JsonPropertyName("value"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Value = null,
    /// <value>Value precision from BCI</value>
    [property:
        JsonPropertyName("precision"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Precision = null
);
