// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

/// <summary>Grouped BCI enrichment varioables</summary>
public record EnrichmentVariableGroup(
    /// <value>BCI group identifier</value>
    [property:
        JsonPropertyName("bciGroupId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? BciGroupId = null,
    /// <value>Group name in Voyado</value>
    [property:
        JsonPropertyName("groupName"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? GroupName = null,
    /// <value>Variables in group</value>
    [property:
        JsonPropertyName("variables"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<EnrichmentVariable>? Variables = null
);
