// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record HypermediaLink(
    [property:
        JsonPropertyName("href"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Href = null,
    [property:
        JsonPropertyName("method"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Method = null,
    [property: JsonPropertyName("rel"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Rel = null
);
