// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record InteractionSchemaResponse(
    [property: JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Id = null,
    [property:
        JsonPropertyName("self"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        InteractionSchemaResponseSelf? Self = null
);
