// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record MultichannelPromotionRedemptionChannelModel(
    [property:
        JsonPropertyName("type"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        MultichannelPromotionRedemptionChannelModel.MultichannelPromotionRedemptionChannelModelType? Type_ =
        null,
    [property:
        JsonPropertyName("valueType"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        MultichannelPromotionRedemptionChannelModel.MultichannelPromotionRedemptionChannelModelValueType? ValueType =
        null,
    /// <value>
    /// The type of "Value" depends on "ValueType".
    /// "MONEY" expects a decimal as a string ("20.5"). "SWIPE", "EXTERNALOFFER" and "MANUAL" expects a string ("Promotion"). "PERCENT" expects an integer as a string ("20").
    /// </value>
    [property:
        JsonPropertyName("value"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Value = null,
    [property:
        JsonPropertyName("localValues"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<object>? LocalValues = null,
    [property:
        JsonPropertyName("instruction"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Instruction = null
)
{
    public record MultichannelPromotionRedemptionChannelModelType : ValueEnum<string>
    {
        internal MultichannelPromotionRedemptionChannelModelType(string value)
            : base(value) { }

        public MultichannelPromotionRedemptionChannelModelType()
            : base("POS") { }

        public static MultichannelPromotionRedemptionChannelModelType Pos = new("POS");
        public static MultichannelPromotionRedemptionChannelModelType Ecom = new("ECOM");
        public static MultichannelPromotionRedemptionChannelModelType Other = new("OTHER");
    }

    public record MultichannelPromotionRedemptionChannelModelValueType : ValueEnum<string>
    {
        internal MultichannelPromotionRedemptionChannelModelValueType(string value)
            : base(value) { }

        public MultichannelPromotionRedemptionChannelModelValueType()
            : base("PERCENT") { }

        public static MultichannelPromotionRedemptionChannelModelValueType Percent = new("PERCENT");
        public static MultichannelPromotionRedemptionChannelModelValueType Money = new("MONEY");
        public static MultichannelPromotionRedemptionChannelModelValueType Externaloffer =
            new("EXTERNALOFFER");
        public static MultichannelPromotionRedemptionChannelModelValueType Manual = new("MANUAL");
        public static MultichannelPromotionRedemptionChannelModelValueType Swipe = new("SWIPE");
    }
}
