// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record MultichannelBasePromotionModel(
    /// <value>
    /// Name of promtion.
    /// Following field is required and don't allows to be left out or set to null or empty string
    /// </value>
    [property: JsonPropertyName("name")]
        string Name,
    /// <value>External id generated from system outside of Voyado</value>
    [property:
        JsonPropertyName("externalId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ExternalId = null,
    /// <value>
    /// Following class holds the duration information for a promotion.
    /// The this object uses to set and get the duration of a promotion.
    /// </value>
    [property:
        JsonPropertyName("validity"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PromotionValidityModel? Validity = null,
    /// <value>
    /// Following object is for get/set the presentational side of the promotion.
    /// This data uses to displey in different kind of views, for an example in Email messages etc.
    ///
    /// This fields populates the "Presentation" section in the admin UI.
    /// </value>
    [property:
        JsonPropertyName("presentation"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        PromotionBasicPresentationModel? Presentation = null,
    /// <value>
    /// Redemption channels
    /// Valid channels: POS, ECOM and OTHER
    /// </value>
    [property:
        JsonPropertyName("redemptionChannels"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<MultichannelPromotionRedemptionChannelModel>? RedemptionChannels = null
);
