// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record OrderContact(
    [property: JsonPropertyName("matchKey")] string MatchKey,
    [property: JsonPropertyName("matchKeyType")] OrderContact.OrderContactMatchKeyType MatchKeyType
)
{
    public record OrderContactMatchKeyType : ValueEnum<string>
    {
        internal OrderContactMatchKeyType(string value)
            : base(value) { }

        public OrderContactMatchKeyType()
            : base("Email") { }

        public static OrderContactMatchKeyType Email = new("Email");
        public static OrderContactMatchKeyType SocialSecurityNumber = new("SocialSecurityNumber");
        public static OrderContactMatchKeyType MobilePhone = new("MobilePhone");
        public static OrderContactMatchKeyType CardId = new("CardId");
        public static OrderContactMatchKeyType ExternalId = new("ExternalId");
        public static OrderContactMatchKeyType MemberNumber = new("MemberNumber");
        public static OrderContactMatchKeyType ContactId = new("ContactId");
        public static OrderContactMatchKeyType MemberNumberWithCardNumberAsFallback =
            new("MemberNumberWithCardNumberAsFallback");
    }
}
