// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record PointAccountPointTransactions2Filter : ValueEnum<string>
{
    internal PointAccountPointTransactions2Filter(string value)
        : base(value) { }

    public PointAccountPointTransactions2Filter()
        : base("All") { }

    public static PointAccountPointTransactions2Filter All = new("All");
    public static PointAccountPointTransactions2Filter Active = new("Active");
    public static PointAccountPointTransactions2Filter Pending = new("Pending");
}
