// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record PointTransactionToAccountResultModel(
    [property:
        JsonPropertyName("notAccepted"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<PointTransactionToAccount>? NotAccepted = null,
    [property:
        JsonPropertyName("errorMessages"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? ErrorMessages = null,
    [property:
        JsonPropertyName("missingDefinitionIds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<long>? MissingDefinitionIds = null,
    [property:
        JsonPropertyName("missingContactIds"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<string>? MissingContactIds = null
);
