// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record ProductViewApiModel(
    [property: JsonPropertyName("itemId")] string ItemId,
    [property: JsonPropertyName("contactId")] string ContactId,
    [property:
        JsonPropertyName("category"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Category = null,
    [property:
        JsonPropertyName("time"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Time = null,
    [property:
        JsonPropertyName("sessionId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? SessionId = null,
    [property:
        JsonPropertyName("newSession"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        bool? NewSession = null,
    [property:
        JsonPropertyName("language"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Language = null,
    [property: JsonPropertyName("url"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Url = null,
    [property:
        JsonPropertyName("externalReferrer"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ExternalReferrer = null,
    [property: JsonPropertyName("utm"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        List<Utm>? Utm = null
);
