// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

/// <summary>
/// Following object is for get/set the presentational side of the promotion.
/// This data uses to displey in different kind of views, for an example in Email messages etc.
///
/// This fields populates the "Presentation" section in the admin UI.
/// </summary>
public record PromotionBasicPresentationModel(
    /// <value>
    /// Heading for the promotion.
    /// Uses to show up in different kind of views.
    /// </value>
    [property:
        JsonPropertyName("heading"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Heading = null,
    /// <value>
    /// Description for the promotion.
    /// Uses to show up in different kind of views.
    /// </value>
    [property:
        JsonPropertyName("description"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Description = null,
    /// <value>
    /// A external link for the promotion.
    /// Uses to show up in different kind of views.
    /// </value>
    [property:
        JsonPropertyName("link"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Link = null
);
