// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

/// <summary>
/// Following class holds the duration information for a promotion.
/// The this object uses to set and get the duration of a promotion.
/// </summary>
public record PromotionValidityModel(
    /// <value>Start date when the promotion going to be active</value>
    [property: JsonPropertyName("startDate")]
        string StartDate,
    /// <value>End date when the promotion not longer active</value>
    [property:
        JsonPropertyName("endDate"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? EndDate = null,
    /// <value>The validity time of the promotion set when assignment occured</value>
    [property:
        JsonPropertyName("assignedValidity"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        AssignDateRange? AssignedValidity = null
);
