// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record PurchaseHistorySummary(
    [property:
        JsonPropertyName("lastUpdated"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? LastUpdated = null,
    [property:
        JsonPropertyName("purchaseAmountAll"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PurchaseAmountAll = null,
    [property:
        JsonPropertyName("numberOfArticlePurchasesAll"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? NumberOfArticlePurchasesAll = null,
    [property:
        JsonPropertyName("averageReceiptAll"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? AverageReceiptAll = null,
    [property:
        JsonPropertyName("latestReceiptDate"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? LatestReceiptDate = null,
    [property:
        JsonPropertyName("purchaseFrequencyAll"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PurchaseFrequencyAll = null,
    [property:
        JsonPropertyName("purchaseAmountLastYear"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PurchaseAmountLastYear = null,
    [property:
        JsonPropertyName("numberOfArticlePurchasesLastYear"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? NumberOfArticlePurchasesLastYear = null,
    [property:
        JsonPropertyName("averageReceiptLastYear"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? AverageReceiptLastYear = null,
    [property:
        JsonPropertyName("purchaseFrequencyLastYear"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PurchaseFrequencyLastYear = null,
    [property:
        JsonPropertyName("purchaseAmountLastTwoYears"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PurchaseAmountLastTwoYears = null,
    [property:
        JsonPropertyName("numberOfArticlePurchasesLastTwoYears"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? NumberOfArticlePurchasesLastTwoYears = null,
    [property:
        JsonPropertyName("averageReceiptLastTwoYears"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? AverageReceiptLastTwoYears = null,
    [property:
        JsonPropertyName("purchaseFrequencyLastTwoYears"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? PurchaseFrequencyLastTwoYears = null
);
