// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record ReceiptPaymentMethod(
    [property: JsonPropertyName("type")] string Type_,
    [property: JsonPropertyName("value")] double Value,
    [property:
        JsonPropertyName("description"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Description = null,
    [property:
        JsonPropertyName("extraData"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ReceiptExtraDataItem>? ExtraData = null
);
