// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record Receipt(
    [property: JsonPropertyName("contact")] ReceiptContact Contact,
    [property: JsonPropertyName("uniqueReceiptId")] string UniqueReceiptId,
    [property: JsonPropertyName("receiptNumber")] string ReceiptNumber,
    [property: JsonPropertyName("createdDate")] string CreatedDate,
    [property: JsonPropertyName("storeExternalId")] string StoreExternalId,
    [property: JsonPropertyName("currency")] string Currency,
    [property: JsonPropertyName("totalGrossPrice")] double TotalGrossPrice,
    [property: JsonPropertyName("paymentMethods")] List<ReceiptPaymentMethod> PaymentMethods,
    [property: JsonPropertyName("items")] List<ReceiptItem> Items,
    [property:
        JsonPropertyName("exchangeRateToGroupCurrency"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        double? ExchangeRateToGroupCurrency = null,
    [property:
        JsonPropertyName("taxDetails"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ReceiptTaxDetail>? TaxDetails = null,
    [property:
        JsonPropertyName("usedBonusChecks"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ReceiptUsedBonusCheck>? UsedBonusChecks = null,
    [property:
        JsonPropertyName("usedPromotions"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ReceiptUsedPromotion>? UsedPromotions = null,
    [property:
        JsonPropertyName("extraData"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        List<ReceiptExtraDataItem>? ExtraData = null
);
