// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record ReceiptUsedPromotion(
    [property:
        JsonPropertyName("promotionId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? PromotionId = null,
    [property:
        JsonPropertyName("couponId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? CouponId = null
);
