// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;
using VoyadoEngage.Json;

namespace VoyadoEngage.Models;

public record ReceiptContact(
    [property: JsonPropertyName("matchKey")] string MatchKey,
    [property: JsonPropertyName("matchKeyType")]
        ReceiptContact.ReceiptContactMatchKeyType MatchKeyType,
    [property:
        JsonPropertyName("contactType"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ContactType = null
)
{
    public record ReceiptContactMatchKeyType : ValueEnum<string>
    {
        internal ReceiptContactMatchKeyType(string value)
            : base(value) { }

        public ReceiptContactMatchKeyType()
            : base("Email") { }

        public static ReceiptContactMatchKeyType Email = new("Email");
        public static ReceiptContactMatchKeyType SocialSecurityNumber = new("SocialSecurityNumber");
        public static ReceiptContactMatchKeyType MobilePhone = new("MobilePhone");
        public static ReceiptContactMatchKeyType CardId = new("CardId");
        public static ReceiptContactMatchKeyType ExternalId = new("ExternalId");
        public static ReceiptContactMatchKeyType MemberNumber = new("MemberNumber");
        public static ReceiptContactMatchKeyType ContactId = new("ContactId");
        public static ReceiptContactMatchKeyType MemberNumberWithCardNumberAsFallback =
            new("MemberNumberWithCardNumberAsFallback");
    }
}
