// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record RedeemBodyModel(
    [property:
        JsonPropertyName("redemptionChannel"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? RedemptionChannel = null
);
