// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record SubscriptionRequest(
    [property:
        JsonPropertyName("contactId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ContactId = null,
    [property: JsonPropertyName("sku"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        string? Sku = null,
    [property:
        JsonPropertyName("locale"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Locale = null,
    [property:
        JsonPropertyName("externalId"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? ExternalId = null
);
