// This file was generated by liblab | https://liblab.com/

using System.Text.Json.Serialization;

namespace VoyadoEngage.Models;

public record UnregisteredFromOnlineRegisterInformation(
    [property:
        JsonPropertyName("reason"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Reason = null,
    [property:
        JsonPropertyName("date"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? Date = null,
    [property:
        JsonPropertyName("newSocialSecurityNumber"),
        JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)
    ]
        string? NewSocialSecurityNumber = null
);
